package com.kigz.javillasafarihub.localization

/**
 * Lightweight in-app localization for the app's navigation and core home/settings UI.
 * English remains the fallback so no functionality is lost when a translation is missing.
 */
fun translate(text: String, language: String): String {
    if (language == "en") return text
    return translations[language]?.get(text) ?: text
}

private val translations: Map<String, Map<String, String>> = mapOf(
    "sw" to mapOf(
        "Javilla Safari Hub" to "Javilla Safari Hub", "Explore. Discover. Experience." to "Chunguza. Gundua. Furahia.",
        "Explore" to "Chunguza", "Planner" to "Mpangaji", "Favorites" to "Vipendwa", "Profile" to "Wasifu",
        "Settings" to "Mipangilio", "Destinations" to "Maeneo", "Activities" to "Shughuli", "Transport" to "Usafiri",
        "Recommended Trips" to "Safari Zinazopendekezwa", "AI Recommendations" to "Mapendekezo ya AI",
        "Emergency & Safety" to "Dharura na Usalama", "Scam Shield & Reports" to "Kinga ya Utapeli na Ripoti",
        "Verified Tourist Services" to "Huduma za Watalii Zilizothibitishwa", "Offline Travel Guide" to "Mwongozo wa Safari Nje ya Mtandao",
        "Tourist Reviews & Ratings" to "Maoni na Ukadiriaji wa Watalii", "Bookings" to "Mahifadhi",
        "Emergency SOS" to "SOS ya Dharura", "Notifications & Safety Alerts" to "Arifa na Tahadhari za Usalama",
        "Budget & Expenses" to "Bajeti na Gharama", "Start your adventure" to "Anza safari yako",
        "Discover destinations, activities, transport options and useful travel tools." to "Gundua maeneo, shughuli, usafiri na zana muhimu za safari.",
        "Explore Javilla Safari Hub" to "Chunguza Javilla Safari Hub", "Wild Beauty of the Safari" to "Uzuri wa Porini wa Safari",
        "Fur patterns, paws and textures up close" to "Miwani ya wanyama, nyayo na maumbo kwa karibu",
        "Search destinations, activities..." to "Tafuta maeneo, shughuli...", "Discover amazing places" to "Gundua maeneo ya ajabu",
        "Find things to do" to "Pata mambo ya kufanya", "Plan your transportation" to "Panga usafiri wako",
        "Plan your trip and calculate budget" to "Panga safari yako na bajeti", "Explore locations" to "Chunguza maeneo",
        "Your saved places" to "Maeneo uliyohifadhi", "Get personalized safari ideas" to "Pata mawazo ya safari binafsi",
        "Get urgent travel safety assistance" to "Pata msaada wa haraka wa usalama wa safari",
        "Check reports and report tourist problems" to "Angalia ripoti na ripoti matatizo ya watalii",
        "Find trusted tourism businesses" to "Pata biashara za utalii zinazoaminika",
        "Essential Kenya travel info without internet" to "Taarifa muhimu za Kenya bila intaneti",
        "Share experiences and discover trusted feedback" to "Shiriki uzoefu na gundua maoni yanayoaminika",
        "Appearance" to "Mwonekano", "Dark Mode" to "Hali ya Giza", "Language" to "Lugha",
        "Account" to "Akaunti", "Account Information" to "Taarifa za Akaunti", "App Links" to "Viungo vya Programu",
        "Logout" to "Ondoka", "Login" to "Ingia", "Close" to "Funga", "Get Started" to "Anza",
        "Press back again to exit" to "Bonyeza nyuma tena ili kutoka", "Search results" to "Matokeo ya utafutaji",
        "No matching destinations or activities found." to "Hakuna maeneo au shughuli zinazolingana zilizopatikana.",
        "Tap a destination result to see all destinations." to "Gonga tokeo la eneo ili kuona maeneo yote.",
        "Logged in as" to "Umeingia kama", "Notifications Settings" to "Mipangilio ya Arifa",
        "Application Info" to "Taarifa za Programu", "Terms & Privacy" to "Masharti na Faragha",
        "No browser is available." to "Hakuna kivinjari kinachopatikana.", "Unable to open the link." to "Imeshindwa kufungua kiungo.",
        "Kenya Destinations" to "Maeneo ya Kenya", "Discover Kenya" to "Gundua Kenya",
        "Explore amazing destinations, wildlife, beaches, mountains and cultural experiences across Kenya." to "Chunguza maeneo ya ajabu, wanyamapori, fukwe, milima na uzoefu wa kitamaduni kote Kenya.",
        "Search destinations..." to "Tafuta maeneo...", "No destinations found" to "Hakuna maeneo yaliyopatikana",
        "Try searching for another destination." to "Jaribu kutafuta eneo lingine.", "Best time:" to "Wakati mzuri:", "Rating:" to "Ukadiriaji:",
        "Open website" to "Fungua tovuti", "No browser is available to open this destination." to "Hakuna kivinjari cha kufungua eneo hili.",
        "Unable to open this destination link." to "Imeshindwa kufungua kiungo cha eneo hili.", "View Details" to "Angalia Maelezo",
        "About" to "Kuhusu", "Travel Information" to "Taarifa za Safari", "Entry Fee" to "Ada ya Kuingia",
        "Free / Check current rates" to "Bure / Angalia viwango vya sasa", "Best Time to Visit" to "Wakati Mzuri wa Kutembelea",
        "Things to Do" to "Mambo ya Kufanya", "Visit Official Website" to "Tembelea Tovuti Rasmi", "Plan a Trip Here" to "Panga Safari Hapa",
        "Safari Activities" to "Shughuli za Safari", "Explore Activities" to "Chunguza Shughuli",
        "Discover exciting things to do during your safari." to "Gundua mambo ya kusisimua ya kufanya wakati wa safari yako.",
        "Search activities..." to "Tafuta shughuli...", "All Activities" to "Shughuli Zote", "Filter by category" to "Chuja kwa kategoria",
        "Clear Filters" to "Futa Vichujio", "No activities found." to "Hakuna shughuli zilizopatikana.",
        "Location:" to "Mahali:", "Price: KSh" to "Bei: KSh", "Trip Planner" to "Mpangaji wa Safari",
        "Plan Your Kenya Safari" to "Panga Safari Yako ya Kenya",
        "Create a personalized safari itinerary by entering your trip details below." to "Unda ratiba ya safari ya kibinafsi kwa kuingiza maelezo ya safari yako hapa chini.",
        "Trip Name" to "Jina la Safari", "e.g. Maasai Mara Safari" to "mfano Safari ya Maasai Mara", "Destination" to "Eneo",
        "e.g. Maasai Mara" to "mfano Maasai Mara", "Start Date" to "Tarehe ya Kuanza", "Select start date" to "Chagua tarehe ya kuanza",
        "End Date" to "Tarehe ya Kumaliza", "Select end date" to "Chagua tarehe ya kumaliza", "Number of Travelers" to "Idadi ya Wasafiri",
        "e.g. 2" to "mfano 2", "Activities" to "Shughuli", "e.g. Game drives, hiking, bird watching" to "mfano Kuangalia wanyama, kupanda milima, kuangalia ndege",
        "Transport" to "Usafiri", "e.g. Safari van, rental car" to "mfano Gari la safari, gari la kukodisha",
        "Estimated Budget" to "Bajeti Inayokadiriwa", "Generated from the Safari Budget Calculator." to "Imetolewa kutoka kwa Kikokotoo cha Bajeti ya Safari.",
        "No budget generated yet." to "Hakuna bajeti iliyotolewa bado.", "Use the Budget Calculator to estimate your trip cost." to "Tumia Kikokotoo cha Bajeti kukadiria gharama za safari yako.",
        "Notes" to "Maelezo", "Add any additional information..." to "Ongeza taarifa yoyote ya ziada...", "Trip Summary" to "Muhtasari wa Safari",
        "Trip:" to "Safari:", "Destination:" to "Eneo:", "Start:" to "Anza:", "End:" to "Mwisho:", "Travelers:" to "Wasafiri:", "Budget:" to "Bajeti:",
        "Save Trip" to "Hifadhi Safari", "Your safari trip has been saved." to "Safari yako imehifadhiwa.", "Saved Trips" to "Safari Zilizohifadhiwa",
        "Your Safari Trips" to "Safari Zako za Safari", "Trips you have saved in Javilla Safari Hub." to "Safari ulizohifadhi katika Javilla Safari Hub.",
        "No Saved Trips" to "Hakuna Safari Zilizohifadhiwa", "Create a trip using the Trip Planner and save it here." to "Unda safari ukitumia Mpangaji wa Safari na uihifadhi hapa.",
        "traveler(s)" to "msafiri(wasafiri)", "Activities:" to "Shughuli:", "Transport:" to "Usafiri:", "Notes:" to "Maelezo:",
        "Safari Map" to "Ramani ya Safari", "Your location" to "Mahali ulipo", "Last known device location" to "Mahali pa mwisho pa kifaa",
        "Allow location to show your position on the map." to "Ruhusu mahali ili kuonyesha nafasi yako kwenye ramani.",
        "Allow Location" to "Ruhusu Mahali", "My Favorites" to "Vipendwa Vyangu", "No favorite destinations" to "Hakuna maeneo pendwa",
        "Save destinations you would like to visit." to "Hifadhi maeneo ambayo ungependa kutembelea.", "My Profile" to "Wasifu Wangu",
        "Display Name" to "Jina la Kuonyeshwa", "Phone Number" to "Namba ya Simu", "Welcome to Javilla Safari Hub" to "Karibu Javilla Safari Hub",
        "Profile updated" to "Wasifu umesasishwa", "Update failed: " to "Usasishaji umeshindwa: ", "Save Profile" to "Hifadhi Wasifu",
        "Edit Profile" to "Hariri Wasifu", "Cancel" to "Ghairi", "Email" to "Barua pepe", "Phone" to "Simu", "Not provided" to "Haijatolewa",
        "My Trips" to "Safari Zangu", "Select Profile Photo" to "Chagua Picha ya Wasifu",
        "Choose a photo from your gallery or take a new one using the camera." to "Chagua picha kutoka kwenye nyumba ya sanaa au piga mpya ukitumia kamera.",
        "Camera" to "Kamera", "Gallery" to "Sanaa", "Tourist Safety & Assistance" to "Usalama na Msaada kwa Watalii",
        "Emergency assistance" to "Msaada wa dharura",
        "If you are in immediate danger, contact the appropriate local emergency service directly. This app does not replace emergency services." to "Ikiwa uko katika hatari ya haraka, wasiliana na huduma ya dharura ya ndani moja kwa moja. Programu hii haichukui nafasi ya huduma za dharura.",
        "Nearby safety alerts" to "Tahadhari za usalama za karibu", "Enable Location" to "Washa Mahali", "Refresh Location" to "Sasisha Mahali",
        "Only reports approved by moderation are shown as alerts. Reports under review are not presented as confirmed incidents." to "Ripoti zilizoidhinishwa tu ndizo zinaonyeshwa kama tahadhari. Ripoti zinazokaguliwa hazionyeshwi kama matukio yaliyothibitishwa.",
        "Verified alerts within 25 km" to "Tahadhari zilizothibitishwa ndani ya km 25",
        "No approved location-aware safety alerts were found nearby." to "Hakuna tahadhari za usalama za karibu zilizopatikana.",
        "Safety Services" to "Huduma za Usalama", "Police Assistance" to "Msaada wa Polisi",
        "Contact police when you experience theft, assault, threats or other criminal incidents." to "Wasiliana na polisi unapokumbana na wizi, shambulio, vitisho au matukio mengine ya jinai.",
        "Medical Assistance" to "Msaada wa Matibabu", "Seek professional medical help for illness, injury or medical emergencies." to "Tafuta msaada wa matibabu wa kitaalamu kwa magonjwa, majeraha au dharura za matibabu.",
        "Transport Safety" to "Usalama wa Usafiri", "Use reputable transport providers and confirm prices before beginning a journey." to "Tumia watoa huduma wa usafiri wanaoaminika na uthibitishe bei kabla ya kuanza safari.",
        "Scam Awareness" to "Uelewa wa Utapeli", "Be cautious of unsolicited offers, unclear prices and requests for unusual payments." to "Kuwa mwangalifu na ofa zisizohitajika, bei zisizoeleweka na maombi ya malipo yasiyo ya kawaida.",
        "Wildlife Safety" to "Usalama wa Wanyamapori", "Follow your guide's instructions and maintain safe distances from wildlife." to "Fuata maelekezo ya kiongozi wako na ukae mbali na wanyamapori.",
        "Report a Safety Incident" to "Ripoti Tukio la Usalama", "Please sign in before reporting an incident." to "Tafadhali ingia kabla ya kuripoti tukio.",
        "Incident submitted for moderation" to "Tukio limewasilishwa kwa ajili ya ukaguzi", "Could not submit incident" to "Imeshindwa kuwasilisha tukio",
        "away • " to "mbali • ", "Confirmed by travellers: " to "Imethibitishwa na wasafiri: ", "I experienced this too" to "Nimepitia hili pia",
        "Reports are reviewed before they can become nearby safety alerts." to "Ripoti zinakaguliwa kabla ya kuwa tahadhari za usalama za karibu.",
        "Location / landmark" to "Mahali / alama", "Verified service ID (optional)" to "Kitambulisho cha huduma iliyothibitishwa (hiari)",
        "Describe what happened" to "Eleza kilichotokea",
        "Your current coordinates will be attached to this report to support location-aware alerts." to "Kuratibu zako za sasa zitaunganishwa kwenye ripoti hii ili kusaidia tahadhari za mahali.",
        "Enable location before submitting if you want this report to support nearby alerts." to "Washa mahali kabla ya kuwasilisha ikiwa unataka ripoti hii kusaidia tahadhari za karibu.",
        "Submit" to "Wasilisha", "Live updates" to "Mabadiliko ya moja kwa moja", "Travel with confidence" to "Safiri kwa ujasiri",
        "Community reports help travellers identify possible scams, overcharging and harassment. Reports are shared only after submission and can be moderated." to "Ripoti za jamii husaidia wasafiri kutambua utapeli unaowezekana, utozaji wa juu na unyanyasaji. Ripoti zinashirikiwa tu baada ya kuwasilishwa na zinaweza kukaguliwa.",
        "Before You Pay" to "Kabla ya Kulipa", "Check the total price and what is included before accepting a service." to "Angalia bei kamili na kilichojumuishwa kabla ya kukubali huduma.",
        "Prefer verified accommodation, guides, transport providers and businesses." to "Pendelea malazi, viongozi, watoa huduma wa usafiri na biashara zilizothibitishwa.",
        "Keep receipts, booking confirmations and payment references." to "Tunza risiti, uthibitisho wa uhifadhi na marejeleo ya malipo.",
        "If something feels unsafe, leave the situation and use Emergency & Safety." to "Ikiwa kitu kinahisi si salama, ondoka kwenye hali hiyo na utumie Dharura na Usalama.",
        "Community Safety Reports" to "Ripoti za Usalama za Jamii", "No community reports yet. Be the first to share a useful warning." to "Hakuna ripoti za jamii bado. Kuwa wa kwanza kushiriki onyo muhimu.",
        "Report a Problem" to "Ripoti Tatizo", "Select a category" to "Chagua kategoria", "Overcharging" to "Utozaji wa juu", "Scam" to "Utapeli",
        "Harassment" to "Unyanyasaji", "Where did it happen?" to "Ilitokea wapi?", "e.g. Diani Beach, Nairobi CBD, Maasai Mara" to "mfano Pwani ya Diani, Nairobi CBD, Maasai Mara",
        "Give factual details. Do not share passwords, card details or other secrets." to "Toa maelezo ya ukweli. Usishiriki nywila, maelezo ya kadi au siri zingine.",
        "Submit Report" to "Wasilisha Ripoti",
        "Reports are stored in Firebase Realtime Database and marked pending for moderation. This module keeps allegations separate from verified reviews and does not present a report as proven fact." to "Ripoti zinahifadhiwa kwenye Firebase na kuwekwa alama ya kusubiri ukaguzi. Moduli hii huweka madai kando na maoni yaliyothibitishwa.",
        "Report submitted" to "Ripoti imewasilishwa",
        "Thank you. Your report has been shared with the community as pending moderation. Please use Emergency & Safety if you are in immediate danger." to "Asante. Ripoti yako imeshirikiwa na jamii ikisubiri ukaguzi. Tafadhali tumia Dharura na Usalama ikiwa uko katika hatari.",
        "Reported by " to "Imeripotiwa na ", "Community verified" to "Imethibitishwa na jamii", "Pending moderation" to "Inasubiri ukaguzi",
        "I experienced this too (" to "Nimepitia hili pia (", "Trusted tourism directory" to "Orodha ya utalii inayoaminika",
        "Service listings are synchronized with Firebase. Verification status is shown separately from community reviews and scam reports." to "Orodha za huduma zinasawazishwa na Firebase. Hali ya uthibitisho inaonyeshwa kando.",
        "Search services" to "Tafuta huduma", "Available services (" to "Huduma zinazopatikana (", "No services match your search." to "Hakuna huduma zinazolingana na utafutaji wako.",
        "Verification is not an endorsement. Production verification should combine business registration/licensing checks, partner validation, community reports and periodic re-verification." to "Uthibitisho si pendekezo. Uthibitisho wa uzalishaji unapaswa kuunganisha ukaguzi wa leseni na ripoti za jamii.",
        "Verified listing" to "Orodha iliyothibitishwa", "Verification pending" to "Uthibitisho unasubiriwa", "Category: " to "Kategoria: ",
        "Location: " to "Mahali: ", "Pricing: " to "Bei: ", "Phone: " to "Simu: ", "Website: " to "Tovuti: ",
        "Safety reminder: confirm the final price, inclusions, cancellation terms and provider identity before payment." to "Kumbusho la usalama: thibitisha bei ya mwisho na utambulisho wa mtoa huduma kabla ya malipo.",
        "No phone app is available." to "Hakuna programu ya simu inayopatikana.", "Unable to open the phone app." to "Imeshindwa kufungua programu ya simu.",
        "Report " to "Ripoti ", "Reports are sent to the moderation queue and are kept separate from reviews and scam allegations." to "Ripoti zinatumwa kwa foleni ya ukaguzi.",
        "Reason" to "Sababu", "Information is inaccurate" to "Taarifa si sahihi", "Provider is no longer operating" to "Mtoa huduma hafanyi kazi tena",
        "Verification appears questionable" to "Uthibitisho unaonekana kutiliwa shaka", "Other" to "Nyingine",
        "Additional details (optional)" to "Maelezo ya ziada (hiari)", "Service report submitted for review" to "Ripoti ya huduma imewasilishwa kwa ukaguzi",
        "Could not submit report" to "Imeshindwa kuwasilisha ripoti", "Submit report" to "Wasilisha ripoti", "Verified" to "Imethibitishwa",
        "Pending verification" to "Inasubiri uthibitisho", "View details" to "Angalia maelezo", "Report" to "Ripoti",
        "Community reviews stored securely online" to "Maoni ya jamii yanahifadhiwa mtandaoni kwa usalama",
        "Sign in to Write a Review" to "Ingia ili kuandika maoni", "Write a Review" to "Andika Maoni", "No reviews available yet." to "Hakuna maoni yanayopatikana bado.",
        "Review submitted for moderation" to "Maoni yamewasilishwa kwa ajili ya ukaguzi", "Could not submit review" to "Imeshindwa kuwasilisha maoni",
        "Recently" to "Hivi karibuni", "stars" to "nyota", "Helpful" to "Inasaidia", " travellers found this helpful" to " wasafiri wameona hii inasaidia",
        "Your experience" to "Uzoefu wako", "Place or service" to "Mahali au huduma", "Safari Budget Calculator" to "Kikokotoo cha Bajeti ya Safari",
        "Plan Your Kenya Safari Budget" to "Panga Bajeti Yako ya Safari ya Kenya",
        "Enter your estimated travel expenses below to calculate the total cost of your trip in Kenyan Shillings (KSh)." to "Ingiza gharama zako za safari unazokadiria hapa chini ili kukokotoa gharama kamili katika Shilingi za Kenya (KSh).",
        "OK" to "Sawa", "Cancel" to "Ghairi",
        "Majestically Discover Kenya" to "Gundua Kenya kwa Utukufu",
        "Welcome to Javilla SafariHub" to "Karibu kwenye Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "Gundua maeneo, shughuli, usafiri na zana muhimu za safari kote Kenya."
    ),
    "es" to mapOf(
        "Explore" to "Explorar", "Planner" to "Planificador", "Favorites" to "Favoritos", "Profile" to "Perfil",
        "Settings" to "Configuración", "Destinations" to "Destinos", "Activities" to "Actividades", "Transport" to "Transporte",
        "Recommended Trips" to "Viajes recomendados", "AI Recommendations" to "Recomendaciones de IA",
        "Emergency & Safety" to "Emergencias y seguridad", "Scam Shield & Reports" to "Protección contra estafas y reportes",
        "Verified Tourist Services" to "Servicios turísticos verificados", "Offline Travel Guide" to "Guía de viaje sin conexión",
        "Tourist Reviews & Ratings" to "Reseñas y valoraciones", "Bookings" to "Reservas", "Emergency SOS" to "SOS de emergencia",
        "Notifications & Safety Alerts" to "Notificaciones y alertas", "Budget & Expenses" to "Presupuesto y gastos",
        "Explore. Discover. Experience." to "Explora. Descubre. Vive.", "Start your adventure" to "Comienza tu aventura",
        "Discover amazing places" to "Descubre lugares increíbles", "Find things to do" to "Encuentra actividades",
        "Plan your transportation" to "Planifica tu transporte", "Explore locations" to "Explora lugares",
        "Your saved places" to "Tus lugares guardados", "Get personalized safari ideas" to "Ideas de safari personalizadas",
        "Appearance" to "Apariencia", "Dark Mode" to "Modo oscuro", "Language" to "Idioma", "Account" to "Cuenta",
        "App Links" to "Enlaces de la app", "Logout" to "Cerrar sesión", "Login" to "Iniciar sesión", "Close" to "Cerrar",
        "Get Started" to "Comenzar", "Press back again to exit" to "Presiona atrás de nuevo para salir",
        "Kenya Destinations" to "Destinos de Kenia", "Discover Kenya" to "Descubre Kenia",
        "Search destinations..." to "Buscar destinos...", "No destinations found" to "No se encontraron destinos",
        "About" to "Acerca de", "Travel Information" to "Información de viaje", "Entry Fee" to "Tarifa de entrada",
        "Things to Do" to "Cosas para hacer", "Visit Official Website" to "Visitar sitio web oficial",
        "Plan a Trip Here" to "Planear un viaje aquí", "Safari Activities" to "Actividades de safari",
        "Explore Activities" to "Explorar actividades", "Search activities..." to "Buscar actividades...",
        "All Activities" to "Todas las actividades", "Filter by category" to "Filtrar por categoría",
        "Clear Filters" to "Limpiar filtros", "Trip Planner" to "Planificador de viajes",
        "Plan Your Kenya Safari" to "Planifica tu safari en Kenia", "Trip Name" to "Nombre del viaje",
        "Destination" to "Destino", "Start Date" to "Fecha de inicio", "End Date" to "Fecha de finalización",
        "Number of Travelers" to "Número de viajeros", "Estimated Budget" to "Presupuesto estimado",
        "Notes" to "Notas", "Trip Summary" to "Resumen del viaje", "Save Trip" to "Guardar viaje",
        "Saved Trips" to "Viajes guardados", "Safari Map" to "Mapa de safari", "Your location" to "Tu ubicación",
        "Allow Location" to "Permitir ubicación", "My Favorites" to "Mis favoritos", "My Profile" to "Mi perfil",
        "Display Name" to "Nombre de pantalla", "Phone Number" to "Número de teléfono", "Email" to "Correo electrónico",
        "Tourist Safety & Assistance" to "Seguridad y asistencia turística", "Emergency assistance" to "Asistencia de emergencia",
        "Enable Location" to "Activar ubicación", "Safety Services" to "Servicios de seguridad",
        "Report a Safety Incident" to "Reportar un incidente de seguridad", "Submit" to "Enviar", "Cancel" to "Cancelar",
        "Scam Shield & Reports" to "Protección contra estafas y reportes", "Travel with confidence" to "Viaja con confianza",
        "Submit Report" to "Enviar reporte", "Verified" to "Verificado", "Report" to "Reportar",
        "Write a Review" to "Escribir una reseña", "OK" to "Aceptar", "Cancel" to "Cancelar",
        "Majestically Discover Kenya" to "Descubre Kenia majestuosamente",
        "Welcome to Javilla SafariHub" to "Bienvenido a Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "Descubre destinos, actividades, transporte y herramientas de viaje útiles en Kenia."
    ),
    "fr" to mapOf(
        "Explore" to "Explorer", "Planner" to "Planificateur", "Favorites" to "Favoris", "Profile" to "Profil",
        "Settings" to "Paramètres", "Destinations" to "Destinations", "Activities" to "Activités", "Transport" to "Transport",
        "Recommended Trips" to "Voyages recommandés", "AI Recommendations" to "Recommandations IA",
        "Emergency & Safety" to "Urgence et sécurité", "Scam Shield & Reports" to "Protection contre les arnaques et rapports",
        "Verified Tourist Services" to "Services touristiques vérifiés", "Offline Travel Guide" to "Guide hors ligne",
        "Tourist Reviews & Ratings" to "Avis et évaluations", "Bookings" to "Réservations", "Emergency SOS" to "SOS d'urgence",
        "Notifications & Safety Alerts" to "Notifications et alertes", "Budget & Expenses" to "Budget et dépenses",
        "Explore. Discover. Experience." to "Explorez. Découvrez. Vivez.", "Start your adventure" to "Commencez votre aventure",
        "Appearance" to "Apparence", "Dark Mode" to "Mode sombre", "Language" to "Langue", "Account" to "Compte",
        "App Links" to "Liens de l'application", "Logout" to "Déconnexion", "Login" to "Connexion", "Close" to "Fermer",
        "Get Started" to "Commencer", "Press back again to exit" to "Appuyez à nouveau sur retour pour quitter",
        "Kenya Destinations" to "Destinations au Kenya", "Discover Kenya" to "Découvrez le Kenya",
        "Search destinations..." to "Rechercher des destinations...", "No destinations found" to "Aucune destination trouvée",
        "About" to "À propos", "Travel Information" to "Informations de voyage", "Entry Fee" to "Frais d'entrée",
        "Things to Do" to "Choses à faire", "Visit Official Website" to "Visiter le site officiel",
        "Plan a Trip Here" to "Planifier un voyage ici", "Safari Activities" to "Activités de safari",
        "Explore Activities" to "Explorer les activités", "Search activities..." to "Rechercher des activités...",
        "All Activities" to "Toutes les activités", "Filter by category" to "Filtrer par catégorie",
        "Clear Filters" to "Effacer les filtres", "Trip Planner" to "Planificateur de voyage",
        "Plan Your Kenya Safari" to "Planifiez votre safari au Kenya", "Trip Name" to "Nom du voyage",
        "Destination" to "Destination", "Start Date" to "Date de début", "End Date" to "Date de fin",
        "Number of Travelers" to "Nombre de voyageurs", "Estimated Budget" to "Budget estimé",
        "Notes" to "Notes", "Trip Summary" to "Résumé du voyage", "Save Trip" to "Enregistrer le voyage",
        "Saved Trips" to "Voyages enregistrés", "Safari Map" to "Carte du safari", "Your location" to "Votre emplacement",
        "Allow Location" to "Autoriser la localisation", "My Favorites" to "Mes favoris", "My Profile" to "Mon profil",
        "Display Name" to "Nom d'affichage", "Phone Number" to "Numéro de téléphone", "Email" to "E-mail",
        "Tourist Safety & Assistance" to "Sécurité et assistance touristique", "Emergency assistance" to "Assistance d'urgence",
        "Enable Location" to "Activer la localisation", "Safety Services" to "Services de sécurité",
        "Report a Safety Incident" to "Signaler un incident de sécurité", "Submit" to "Envoyer", "Cancel" to "Annuler",
        "Scam Shield & Reports" to "Protection contre les arnaques et rapports", "Travel with confidence" to "Voyagez en toute confiance",
        "Submit Report" to "Envoyer le rapport", "Verified" to "Vérifié", "Report" to "Signaler",
        "Write a Review" to "Écrire un avis", "OK" to "OK", "Cancel" to "Annuler",
        "Majestically Discover Kenya" to "Découvrez le Kenya majestueusement",
        "Welcome to Javilla SafariHub" to "Bienvenue sur Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "Découvrez des destinations, des activités, des transports et des outils de voyage utiles au Kenya."
    ),
    "de" to mapOf(
        "Explore" to "Entdecken", "Planner" to "Planer", "Favorites" to "Favoriten", "Profile" to "Profil",
        "Settings" to "Einstellungen", "Destinations" to "Reiseziele", "Activities" to "Aktivitäten", "Transport" to "Transport",
        "Recommended Trips" to "Empfohlene Reisen", "AI Recommendations" to "KI-Empfehlungen",
        "Emergency & Safety" to "Notfall und Sicherheit", "Scam Shield & Reports" to "Betrugsschutz und Meldungen",
        "Verified Tourist Services" to "Verifizierte Touristendienste", "Offline Travel Guide" to "Offline-Reiseführer",
        "Tourist Reviews & Ratings" to "Bewertungen und Rezensionen", "Bookings" to "Buchungen", "Emergency SOS" to "Notfall-SOS",
        "Notifications & Safety Alerts" to "Benachrichtigungen und Sicherheitswarnungen", "Budget & Expenses" to "Budget und Ausgaben",
        "Explore. Discover. Experience." to "Erkunden. Entdecken. Erleben.", "Start your adventure" to "Starte dein Abenteuer",
        "Appearance" to "Darstellung", "Dark Mode" to "Dunkelmodus", "Language" to "Sprache", "Account" to "Konto",
        "App Links" to "App-Links", "Logout" to "Abmelden", "Login" to "Anmelden", "Close" to "Schließen",
        "Get Started" to "Loslegen", "Press back again to exit" to "Noch einmal zurück zum Verlassen",
        "Kenya Destinations" to "Kenia Reiseziele", "Discover Kenya" to "Kenia entdecken",
        "Search destinations..." to "Reiseziele suchen...", "No destinations found" to "Keine Reiseziele gefunden",
        "About" to "Über", "Travel Information" to "Reiseinformationen", "Entry Fee" to "Eintrittsgebühr",
        "Things to Do" to "Aktivitäten", "Visit Official Website" to "Offizielle Website besuchen",
        "Plan a Trip Here" to "Hier Reise planen", "Safari Activities" to "Safari-Aktivitäten",
        "Explore Activities" to "Aktivitäten erkunden", "Search activities..." to "Aktivitäten suchen...",
        "All Activities" to "Alle Aktivitäten", "Filter by category" to "Nach Kategorie filtern",
        "Clear Filters" to "Filter löschen", "Trip Planner" to "Reiseplaner",
        "Plan Your Kenya Safari" to "Plane deine Kenia-Safari", "Trip Name" to "Reisename",
        "Destination" to "Ziel", "Start Date" to "Startdatum", "End Date" to "Enddatum",
        "Number of Travelers" to "Anzahl der Reisenden", "Estimated Budget" to "Geschätztes Budget",
        "Notes" to "Notizen", "Trip Summary" to "Reisezusammenfassung", "Save Trip" to "Reise speichern",
        "Saved Trips" to "Gespeicherte Reisen", "Safari Map" to "Safari-Karte", "Your location" to "Dein Standort",
        "Allow Location" to "Standort zulassen", "My Favorites" to "Meine Favoriten", "My Profile" to "Mein Profil",
        "Display Name" to "Anzeigename", "Phone Number" to "Telefonnummer", "Email" to "E-Mail",
        "Tourist Safety & Assistance" to "Touristische Sicherheit & Hilfe", "Emergency assistance" to "Notfallhilfe",
        "Enable Location" to "Standort aktivieren", "Safety Services" to "Sicherheitsdienste",
        "Report a Safety Incident" to "Sicherheitsvorfall melden", "Submit" to "Senden", "Cancel" to "Abbrechen",
        "Scam Shield & Reports" to "Betrugsschutz und Meldungen", "Travel with confidence" to "Sicher reisen",
        "Submit Report" to "Meldung senden", "Verified" to "Verifiziert", "Report" to "Melden",
        "Write a Review" to "Bewertung schreiben", "OK" to "OK", "Cancel" to "Abbrechen",
        "Majestically Discover Kenya" to "Entdecken Sie Kenia majestätisch",
        "Welcome to Javilla SafariHub" to "Willkommen bei Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "Entdecken Sie Reiseziele, Aktivitäten, Transportmittel und nützliche Reisewerkzeuge in Kenia."
    ),
    "zh" to mapOf(
        "Explore" to "探索", "Planner" to "行程规划", "Favorites" to "收藏", "Profile" to "个人资料",
        "Settings" to "设置", "Destinations" to "目的地", "Activities" to "活动", "Transport" to "交通",
        "Recommended Trips" to "推荐行程", "AI Recommendations" to "AI 推荐",
        "Emergency & Safety" to "紧急情况与安全", "Scam Shield & Reports" to "防诈骗与报告",
        "Verified Tourist Services" to "经过验证的旅游服务", "Offline Travel Guide" to "离线旅行指南",
        "Tourist Reviews & Ratings" to "游客评论与评分", "Bookings" to "预订", "Emergency SOS" to "紧急 SOS",
        "Notifications & Safety Alerts" to "通知与安全警报", "Budget & Expenses" to "预算与支出",
        "Explore. Discover. Experience." to "探索、发现、体验。", "Start your adventure" to "开始您的冒险",
        "Appearance" to "外观", "Dark Mode" to "深色模式", "Language" to "语言", "Account" to "账户",
        "App Links" to "应用链接", "Logout" to "退出登录", "Login" to "登录", "Close" to "关闭",
        "Get Started" to "开始", "Press back again to exit" to "再次按返回键退出",
        "Kenya Destinations" to "肯尼亚目的地", "Discover Kenya" to "发现肯尼亚",
        "Search destinations..." to "搜索目的地...", "No destinations found" to "未找到目的地",
        "About" to "关于", "Travel Information" to "旅行信息", "Entry Fee" to "门票",
        "Things to Do" to "必做之事", "Visit Official Website" to "访问官方网站",
        "Plan a Trip Here" to "在此规划行程", "Safari Activities" to "野生动物园活动",
        "Explore Activities" to "探索活动", "Search activities..." to "搜索活动...",
        "All Activities" to "所有活动", "Filter by category" to "按类别筛选",
        "Clear Filters" to "清除筛选", "Trip Planner" to "旅行规划器",
        "Plan Your Kenya Safari" to "规划您的肯尼亚野生动物园之旅", "Trip Name" to "行程名称",
        "Destination" to "目的地", "Start Date" to "开始日期", "End Date" to "结束日期",
        "Number of Travelers" to "旅客人数", "Estimated Budget" to "预估预算",
        "Notes" to "备注", "Trip Summary" to "行程摘要", "Save Trip" to "保存行程",
        "Saved Trips" to "已保存行程", "Safari Map" to "野生动物园地图", "Your location" to "您的位置",
        "Allow Location" to "允许访问位置", "My Favorites" to "我的收藏", "My Profile" to "我的个人资料",
        "Display Name" to "显示名称", "Phone Number" to "电话号码", "Email" to "电子邮件",
        "Tourist Safety & Assistance" to "游客安全与协助", "Emergency assistance" to "紧急协助",
        "Enable Location" to "启用位置", "Safety Services" to "安全服务",
        "Report a Safety Incident" to "报告安全事件", "Submit" to "提交", "Cancel" to "取消",
        "Scam Shield & Reports" to "防诈骗与报告", "Travel with confidence" to "放心旅行",
        "Submit Report" to "提交报告", "Verified" to "已验证", "Report" to "报告",
        "Write a Review" to "撰写评论", "OK" to "确定", "Cancel" to "取消",
        "Majestically Discover Kenya" to "庄严地发现肯尼亚",
        "Welcome to Javilla SafariHub" to "欢迎来到 Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "探索肯尼亚的目的地、活动、交通和实用的旅游工具。"
    ),
    "ar" to mapOf(
        "Explore" to "استكشاف", "Planner" to "المخطط", "Favorites" to "المفضلة", "Profile" to "الملف الشخصي",
        "Settings" to "الإعدادات", "Destinations" to "الوجهات", "Activities" to "الأنشطة", "Transport" to "النقل",
        "Recommended Trips" to "الرحلات الموصى بها", "AI Recommendations" to "توصيات الذكاء الاصطناعي",
        "Emergency & Safety" to "الطوارئ والسلامة", "Scam Shield & Reports" to "درع الاحتيال والتقارير",
        "Verified Tourist Services" to "الخدمات السياحية المعتمدة", "Offline Travel Guide" to "دليل السفر بدون إنترنت",
        "Tourist Reviews & Ratings" to "تقييمات وآراء السياح", "Bookings" to "الحجوزات", "Emergency SOS" to "طوارئ SOS",
        "Notifications & Safety Alerts" to "التنبيهات والإشعارات", "Budget & Expenses" to "الميزانية والمصاريف",
        "Explore. Discover. Experience." to "استكشف. اكتشف. جرب.", "Start your adventure" to "ابدأ مغامرتك",
        "Appearance" to "المظهر", "Dark Mode" to "الوضع الداكن", "Language" to "اللغة", "Account" to "الحساب",
        "App Links" to "روابط التطبيق", "Logout" to "تسجيل الخروج", "Login" to "تسجيل الدخول", "Close" to "إغلاق",
        "Get Started" to "ابدأ", "Press back again to exit" to "اضغط مرة أخرى للخروج",
        "Kenya Destinations" to "وجهات كينيا", "Discover Kenya" to "اكتشف كينيا",
        "Search destinations..." to "البحث عن وجهات...", "No destinations found" to "لم يتم العثور على وجهات",
        "About" to "حول", "Travel Information" to "معلومات السفر", "Entry Fee" to "رسوم الدخول",
        "Things to Do" to "أنشطة للقيام بها", "Visit Official Website" to "زيارة الموقع الرسمي",
        "Plan a Trip Here" to "خطط لرحلة هنا", "Safari Activities" to "أنشطة السفاري",
        "Explore Activities" to "استكشاف الأنشطة", "Search activities..." to "البحث عن أنشطة...",
        "All Activities" to "جميع الأنشطة", "Filter by category" to "تصفية حسب الفئة",
        "Clear Filters" to "مسح التصفية", "Trip Planner" to "مخطط الرحلة",
        "Plan Your Kenya Safari" to "خطط لرحلة سفاري في كينيا", "Trip Name" to "اسم الرحلة",
        "Destination" to "الوجهة", "Start Date" to "تاريخ البدء", "End Date" to "تاريخ الانتهاء",
        "Number of Travelers" to "عدد المسافرين", "Estimated Budget" to "الميزانية التقديرية",
        "Notes" to "ملاحظات", "Trip Summary" to "ملخص الرحلة", "Save Trip" to "حفظ الرحلة",
        "Saved Trips" to "الرحلات المحفوظة", "Safari Map" to "خريطة السفاري", "Your location" to "موقعك",
        "Allow Location" to "السماح بالوصول للموقع", "My Favorites" to "المفضلة", "My Profile" to "ملفي الشخصي",
        "Display Name" to "الاسم المستعار", "Phone Number" to "رقم الهاتف", "Email" to "البريد الإلكتروني",
        "Tourist Safety & Assistance" to "سلامة ومساعدة السياح", "Emergency assistance" to "مساعدة الطوارئ",
        "Enable Location" to "تفعيل الموقع", "Safety Services" to "خدمات السلامة",
        "Report a Safety Incident" to "الإبلاغ عن حادث أمني", "Submit" to "إرسال", "Cancel" to "إلغاء",
        "Scam Shield & Reports" to "درع الاحتيال والتقارير", "Travel with confidence" to "سافر بثقة",
        "Submit Report" to "إرسال تقرير", "Verified" to "موثق", "Report" to "إبلاغ",
        "Write a Review" to "كتابة تقييم", "OK" to "موافق", "Cancel" to "إلغاء",
        "Majestically Discover Kenya" to "اكتشف كينيا بشكل مهيب",
        "Welcome to Javilla SafariHub" to "مرحباً بك في Javilla SafariHub",
        "Discover destinations, activities, transport and useful travel tools across Kenya." to "اكتشف الوجهات والأنشطة ووسائل النقل وأدوات السفر المفيدة في جميع أنحاء كينيا."
    ),
    "pt" to mapOf("Explore" to "Explorar","Planner" to "Planejador","Favorites" to "Favoritos","Profile" to "Perfil","Settings" to "Configurações","Destinations" to "Destinos","Activities" to "Atividades","Transport" to "Transporte","Language" to "Idioma","Dark Mode" to "Modo escuro","Logout" to "Sair","Login" to "Entrar","Get Started" to "Começar"),
    "hi" to mapOf("Explore" to "अन्वेषण","Planner" to "योजनाकार","Favorites" to "पसंदीदा","Profile" to "प्रोफ़ाइल","Settings" to "सेटिंग्स","Destinations" to "गंतव्य","Activities" to "गतिविधियाँ","Transport" to "परिवहन","Language" to "भाषा","Dark Mode" to "डार्क मोड","Logout" to "लॉग आउट","Login" to "लॉगिन","Get Started" to "शुरू करें"),
    "ko" to mapOf("Explore" to "탐색","Planner" to "플래너","Favorites" to "즐겨찾기","Profile" to "프로필","Settings" to "설정","Destinations" to "여행지","Activities" to "활동","Transport" to "교통","Language" to "언어","Dark Mode" to "다크 모드","Logout" to "로그아웃","Login" to "로그인","Get Started" to "시작하기"),
    "ja" to mapOf("Explore" to "探索","Planner" to "プランナー","Favorites" to "お気に入り","Profile" to "プロフィール","Settings" to "設定","Destinations" to "目的地","Activities" to "アクティビティ","Transport" to "交通","Language" to "言語","Dark Mode" to "ダークモード","Logout" to "ログアウト","Login" to "ログイン","Get Started" to "開始")
)
